### ISSUE TITLE
docker socket on OSX is not present on /var/run

### ISSUE THREAD

**Issue by luisgarciaalanis** [opctl/opctl#1080]
## 🐛 Bug Report

Noticed this error:
$> opctl run db
[d24d66ed ./.opspec/db] started op
[7add9f18 ./.opspec/db/init] started op
[1a2331cf ./.opspec/test/init] started op
[707eee23 ./.opspec/test/init] started docker.io/library/alpine:3.14.2
[707eee23 ./.opspec/test/init] docker.io/library/alpine:3.14.2 crashed: unable to inspect network: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
....

on the computer the docker.sock was son $HOME/.docker/run/docker.sock
the /var/run had no file present

Before reporting an issue please remember:
-  One issue, one bug: Please report a single bug per issue.

## To Reproduce

(Write your steps here:)

1. run a op

## Expected behavior

op to run

## Actual Behavior

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by luisgarciaalanis** [comment]
I created a symlink from the home socket to var and it ran.

This happened after a  crash, like if the socket was there then it got erased, but seems that the valid one is on the user home

**Comment by luisgarciaalanis** [comment]
Happened twice

**Comment by chrisdostert** [comment]
Is .opspec/test/init trying to connect to docker? It's not completely clear from the logs but reads like something in that container can't reach docker so is exiting non-zero ```[707eee23 ./.opspec/test/init] docker.io/library/alpine:3.14.2 crashed: unable to inspect network: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?```

**Comment by chrisdostert** [comment]
Maybe another leading question to help track down, Is it always that specific op and that specific container or does it vary?

**Comment by chrisdostert** [comment]
Gonna close this out as a general docker setup issue not opctl.
