### ISSUE TITLE
Print cause of failure

### ISSUE THREAD

**Issue by tomaszhrem** [opctl/opctl#1081]
## 🚀 Feature

When some of image/op would fail fail to start print on console error details.
Print error which occurred if thats is problem within opctl  or image can't start at all.
Alternative could be adding some debug/verbose option to opctl which would help to understand what is causing problem with running.
## Motivation

Currently when there is error opctl does not include any hint what was wrong.
E.g. I moved some ref declarations to other file so I can reuse and after it only what I get its message that "child call failed". There is nothing I can use to debug.
```
% opctl run dev-dependencies
[c466c00c ./.opspec/dev-dependencies] started op
[9ec87ee0 ./.opspec/dev-dependencies] started docker.io/library/redis
[9ec87ee0 ./.opspec/dev-dependencies] docker.io/library/redis killed
[c466c00c ./.opspec/dev-dependencies] op failed: child call failed
┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
◎ ⚠ ./.opspec/dev-dependencies 6.898ms
└─◎ ⚠ parallel 5.106ms
  ├─◉️ ☒ 9ec87ee0 redis 4.964ms
  └─◉ ☐
```
In this case problem was with not existing variable used to configure 'REGION: $(configVarsObject.AWS_REGION)`

**Comment by chrisdostert** [comment]
@tomaszhrem are you using the latest opctl version (0.1.52)? If not please try it and see if that behaves how you expect.
