### ISSUE TITLE
Add read from file as a new input source

### ISSUE THREAD

**Issue by petedv** [opctl/opctl#176]
Similar to using a .env file to supply environment variable values.  
It would be great if we could optionally supply values via file.

This would allow fast swapping between environments by using different files  
And some usability improvements when an op has a substantial amount of inputs.

E.g. Input sources:
 - arg provided via -a option
 - **.env file** <- New option
 - env var
 - default
 - prompt

**Comment by chrisdostert** [comment]
@zachpuck @psamaan @sai-li 
think you guys had asked about this too

**Comment by chrisdostert** [comment]
@petedv what do you think would be best format? 

docker run does it like:
[docker run --env-file](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file)

but i'm also thinking maybe yaml would be better (from a syntax highlighting perspective) and we use yaml everywhere already

thoughts?

**Comment by sai-li** [comment]
+1 for yaml

2017年4月20日 下午3:55，"Chris Dostert" <notifications@github.com>写道：

**Comment by poppuyo** [comment]
+1, this would be cool to help write test ops that can be reusable for multiple scenarios as defined by each input file
