### ISSUE TITLE
Add support for windows container file binding

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#207]
per https://github.com/moby/moby/issues/30555 this appears to not be natively supported; we might have to get creative.

**Comment by Drewster727** [comment]
Any update on this guys?

**Comment by chrisdostert** [comment]
No, it's an annoyance but hasn't been a fire for anyone so fingers have remained crossed that it would be fixed upstream at some point. : /

**Comment by chrisdostert** [comment]
This shouldn't apply to WSL [which we're recommending now](https://github.com/opctl/opctl/blob/main/website/docs/setup/bare-metal.md#windows) so closing this out
