### ISSUE TITLE
init op intermittently doesn't see global gitconfig file 

### ISSUE THREAD

**Issue by DZwell** [opctl/opctl#254]
It presents me with this message:

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

Even though I have a global gitconfig file with this data in there

**Comment by chrisdostert** [comment]
closing as surely an issue w/ VM file syncing
