### ISSUE TITLE
Auto node creation requires opctl bin within path

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#363]
## Repro steps
1) run `opctl node kill`
1) rename opctl binary to 'broke_opctl'
1) run `broke_opctl events`

## Expected
opctl auto creates a node and listens for events

## Actual
error returned `exec: "opctl": executable file not found in $PATH`

**Comment by chrisdostert** [comment]
@psamaan

**Comment by psamaan** [comment]
Can confirm this is resolved on alpha build 0.1.22-alpha.61
