### ISSUE TITLE
Option to clear streams in the browser Ops

### ISSUE THREAD

**Issue by SudhindraKovalam** [opctl/opctl#399]
Need an option to clear the events printed in the op window/console for chatty ops

**Comment by SudhindraKovalam** [comment]
Also, 
when the browser is launched, Need a way to figure out which ops are running or not.
## current behavior
events are replayed, eventhough the op is not running
## expected
The user has a choice, whether s/he sees the event stream replayed or see a clean slate.

**Comment by chrisdostert** [comment]
stale
