### ISSUE TITLE
Running a non-existant op, does not error out

### ISSUE THREAD

**Issue by SudhindraKovalam** [opctl/opctl#407]
In previous build, if we `opctl run` a non existent op, there would be a error suggesting that the op doesnot exist. In the current alpha build `0.1.24-alpha.79` we dont see this anymore. The terminal just sits there and doesnot error out.

## current behavior
`opctl run <non existant op>` doesnot error out

## expected behavior
there should be an error indicating that the op doesnot exist

**Comment by chrisdostert** [comment]
Thank you for filing this!

**Comment by chrisdostert** [comment]
upstream regression: https://github.com/sethgrid/pester/issues/28
fixed by: https://github.com/sethgrid/pester/pull/29
