### ISSUE TITLE
Unable to resolve pkg 'hello-world';

### ISSUE THREAD

**Issue by v-dev** [opctl/opctl#456]
I'm just trying to follow the instructions here:
https://opctl.io/docs/getting-started/hello-world.html

I copied/pasted (using nano) the first `op.yml` inside a `hello-world` directory, ran `opctl run hello-world`, and got:

    Unable to resolve pkg 'hello-world'; error was Get https://hello-world/info/refs?service=git-upload-pack: dial tcp: lookup hello-world on 127.0.0.53:53: server misbehaving

Here's some info of my system:
```
vagrant@vagrant:/sourcecode/opspec/hello-world$ uname -a
Linux vagrant 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant:/sourcecode/opspec/hello-world$ opctl --version
0.1.24
vagrant@vagrant:/sourcecode/opspec/hello-world$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:51 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:23:15 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

Using standard docker commands works ok:
```
vagrant@vagrant:/sourcecode/opspec/hello-world$ docker run alpine:3.6 echo "hello world"
hello world
```

Any ideas what I'm doing wrong?

**Comment by psamaan** [comment]
It's because you're in the sourcecode/opspec/hello-world. Opctl just uses regular relative path resolution. You can just do `opctl run ../` or alternatively `cd ..; opctl run hello-world`

**Comment by v-dev** [comment]
Oh geez - I could have sworn I tried from the parent directory as well.  Apparently not because it works... thanks!

Just a note: the instructions weren't very specific which directory I should be in.  It says, "from your working directory," but makes the assumption that people wouldn't `cd` into the `hello-world` directory to create `op.yml`.

**Comment by psamaan** [comment]
Will address that in the doc. Thanks!

**Comment by chrisdostert** [comment]
@psamaan feel free to address it in the docs; closing this ticket in the meantime as this is resolved
