### ISSUE TITLE
File/Dir attribute dereferencing to make file.path or file.name usable in pkg

### ISSUE THREAD

**Issue by petedv** [opctl/opctl#502]
Use case: 
I'm sharing the docker.sock and starting containers within an op.
If I want to mount a volume for a child container I need the host path.
This leads to requiring two inputs with the same value to run the op.
The directory and a string containing the path to that same directory.

It would be nice to allow reference file or directory names or paths in the package in environment variables.

**Comment by chrisdostert** [comment]
recommendation for this particular use case is to use DIND (example: https://github.com/opspec-pkgs/docker.image.build/blob/master/cmd.sh) so the paths match
