### ISSUE TITLE
vscode intellisense error

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#615]
## Repro
1. https://opctl.io/docs/setup#vscode
1. create a minimal valid `op.yml`

## Expected
1. no red squiggleys

## Actual
1. red squiggleys on first character of file due to vscode not being able to fully interpret the schema. If u hover over it u see:
![image](https://user-images.githubusercontent.com/2335774/61262150-17748f00-a739-11e9-8f18-8c84c45a36bf.png)

## Possible Causes
1. vscode yaml plugin can't handle patternProperties 
2. the way we merge all our schemas into one schema isn't generating a proper schema see [opspec/opfile/.opspec/build](https://github.com/opctl/opctl/tree/master/opspec/opfile/.opspec/build)

**Comment by SudhindraKovalam** [comment]
the vscode yaml plugin seems to support schemas defined at https://github.com/SchemaStore/schemastore. This is a community driven collection of valid yaml/json/css schemas.

Have raised a PR to add our latest JSON schema here.
https://github.com/SchemaStore/schemastore/pull/741

Once this merges in, I can validate if the yaml plugin can officially validate an op schema

**Comment by chrisdostert** [comment]
you can load a schema from anywhere on the web, that's what we're doing in step 1 of the repro steps. It loads the schema fine but it has problems with part of the schema as shown in the attached screenshot
