### ISSUE TITLE
Return ref instead of name from opctl ls

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#634]
Reproduction:

Create this opspec in the file path `.opspec/bar/op.yml`:
```yml
description: |
  Which name should I use?
name: foo
run:
  container:
    image: { ref: 'alpine' }
    cmd: ['echo', 'hello world']
```

```
cameronlittle@Chehalis:~/Dev/platform (±opctl)
▻ opctl ls
NAME	VERSION	DESCRIPTION
foo		Which name should I use?

getemail		Gets your email through the magic of forge. Doesn't work yet - https://github.com/opctl/opctl/issues/633

cameronlittle@Chehalis:~/Dev/test (±opctl)
▻ opctl run foo
Unable to resolve pkg 'foo'; error was Get https://foo/info/refs?service=git-upload-pack: dial tcp: lookup foo on 188.117.188.117:53: no such host

cameronlittle@Chehalis:~/Dev/test (±opctl)
▻ opctl run bar
OpStarted Id='b6a84ab9780842aa9529a74f07402f11' OpRef='/Users/cameronlittle/Dev/test/.opspec/bar' Timestamp='2019-09-30T08:51:40Z'

ContainerStarted Id='767f5a6592894431a6d0f8e4225dc619' OpRef='/Users/cameronlittle/Dev/test/.opspec/bar' Timestamp='2019-09-30T08:51:40Z'

hello world
ContainerExited Id='767f5a6592894431a6d0f8e4225dc619' OpRef='/Users/cameronlittle/Dev/test/.opspec/bar' ExitCode='0' Timestamp='2019-09-30T08:51:57Z'

OpEnded Id='b6a84ab9780842aa9529a74f07402f11' OpRef='/Users/cameronlittle/Dev/test/.opspec/bar' Outcome='SUCCEEDED' Timestamp='2019-09-30T08:51:57Z'


```

The core issue here is that the name presented in `opctl ls` can't be run as an op. There's a difference between the opspec directory name, which is actually required when running the op, and the op's self-described name, which is shown when listing ops. I'm required to inspect the implementation of the op in order to know how to run it, which is a problem.

**Comment by chrisdostert** [comment]
Thanks for opening this. 

The confusion comes from the semantics of name vs reference. 

see [name](https://opctl.io/docs/opspec#name) and [ref](https://opctl.io/docs/commands#op_ref).

We've talked, but not taken as far as actioning, that it could make sense to return ref from `opctl ls` instead of name since that's maybe what is more useful in that context.

@apexskier what're your opinions/thoughts?
