### ISSUE TITLE
Make ls Command Error Msg Better

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#639]
if I `opctl ls` from a directory w/out a `.opspec` directory, the error I get is `Unable to resolve pkg '.opspec'; error was Get https://.opspec/info/refs?service=git-upload-pack: dial tcp: lookup .opspec: no such host`

This isn't intuitive or helpful. 
It should likely just state no `.opspec` found

**Comment by apexskier** [comment]
Resolved by https://github.com/opctl/opctl/pull/883
