### ISSUE TITLE
EnvVars missing from Container in Syntax section of opspec website

### ISSUE THREAD

**Issue by drewandersen** [opctl/opctl#644]
https://opctl.io/docs/opspec#syntax

![image](https://user-images.githubusercontent.com/2484277/66491047-bfb79c80-ea77-11e9-9c0e-cf41dfa00e9a.png)

Does appear correctly in the expanded container definition: https://opctl.io/docs/opspec#container

**Comment by chrisdostert** [comment]
Thanks for filing. 

FYI: If in the future you wanna PR up the docs...
You can hack on the website/docs locally by cd'ing to website dir and `opctl run dev`. Editing docs will trigger live reload as you edit them.
