### ISSUE TITLE
`opctl node kill` should cleanup all resources

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#658]
`opctl node kill` killed my running ops with the error `Event channel closed unexpectedly`

However, my op's container is still running (visible from `docker ps`) which means I can't restart it because of port conflicts.

I'd expect `opctl node kill` to clean up after itself.

**Comment by chrisdostert** [comment]
@apexskier thanks for filing.

This is again one that's been kicked around and has mixed opinions; please add yours. 

**Considerations**:
If you're running an op that is hosting your application in prod and opctl dies/is restarted, should your app die? probably don't want it to.

`opctl node kill` is a different scenario than above. I could probably be convinced it should clean everything up.

**Comment by apexskier** [comment]
> If you're running an op that is hosting your application in prod and opctl dies/is restarted, should your app die?

If it dies, yes, my app should die - opctl is the core runtime, if it's dead something's gone terribly wrong and everything should die

A graceful restart option might be a different use case - in that case it should be able to reconnect to running ops

---

I might be misunderstanding what a `node` is. I might actually be looking for an `opctl op kill` command, where I can kill an op by id.

**Comment by chrisdostert** [comment]
yeah after thinking about this more your original sentiment is 100% right. `opctl node kill` should definitely clean everything up. 

Graceful restart for upgrade or otherwise is a different thing entirely. 

p.s. there is an `opctl op kill` command; see  https://opctl.io/docs/commands#op-kill-op_id-since-v0115

**Comment by apexskier** [comment]
`opctl op kill` is useful, but wouldn't have helped me in this case since I didn't know my ops ID.

**Comment by chrisdostert** [comment]
there's been discussion about this referencing other products like EC2, vagrant, or even k8s.
The command `kill` is ambiguous. Does that mean destroy/delete or just turn off (w/ ability to turn back on later).

**Comment by chrisdostert** [comment]
in #987 I've renamed `opctl node kill` to `opctl node stop` and added `opctl node delete`, which should close this.
