### ISSUE TITLE
CLI: No way to tell which op output comes from

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#664]
Opctl's output is really difficult to understand right now, since there's no way to tell which op is emitting which output (either visually, or through `| grep` or something).

A simple way to improve this would be by prefixing each line with the op's name and ID.

A good example of this done well (for me), is the tool `concurrently`'s ["Prefix styling" options](https://github.com/kimmobrunfeldt/concurrently#usage).

Related to #62

**Comment by chrisdostert** [comment]
@apexskier thanks for filing. Agreed.

From an implementation perspective the primitives are all there; the CLI already subscribes to the op event stream (via the node API over websockets) and prints out the data of ContainerStd[Out/Err]WrittenTo (which include callID attribute too) unmodified, so adding a prefix is straightforward.

The hold up has been deciding:

- if we want it to be prefixed by callID/name/.. other
- if we want it to observe any hierarchy or just be flat (similar consideration as [the ps/pstree ticket](https://github.com/opctl/opctl/issues/657))
- what we want to do about status spinners (this will make them not spin cuz it will interrupt the character sequence). 

I think the ultimate interface will be the UI where you'll be able to debug via a visual/interactive WYSIWYG representation of the graph as it executes and zero in on status and logs of each particular call of the graph. Either way I 100% agree we still should enhance the CLI as well.
