### ISSUE TITLE
Can't develop locally

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#691]
I'm unable to build the cli locally. I've reviewed the contribution documentation.

From the cli directory, I first tried `go build` and got this error:
```
go: downloading github.com/jawher/mow.cli v1.1.0
go: downloading github.com/golang-interfaces/ios v0.0.0-20170803194714-da59acb78efc
... # trimmed for readability
go: finding gopkg.in/warnings.v0 v0.1.2
go: finding github.com/pelletier/go-buffruneio v0.2.0
# github.com/mtrmac/gpgme
../../../go/pkg/mod/github.com/mtrmac/gpgme@v0.0.0-20170102180018-b2432428689c/data.go:4:11: fatal error: 'gpgme.h' file not found
 #include <gpgme.h>
          ^~~~~~~~~
1 error generated.
2 ↩
```

I then tried running the `opctl run dev` op from the cli directory and got this error because I hadn't run `opctl run build` first.
```
OpStarted Id='d9221ab45dd841af8bef461c39ff2405' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Timestamp='2020-02-14T12:10:25Z'

ContainerStarted Id='1b2b5aff4e3c477c9b41f55336b0f4d2' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Timestamp='2020-02-14T12:10:25Z'

1.13: Pulling from library/golang
... # ommitted
530350156010: Pull complete
Digest: sha256:9295ba678e3764d79ac0aeabdbcf281a91933c81c8de29387d8a2f557e256cdb
Status: Downloaded newer image for golang:1.13
API server listening at: [::]:40000
could not launch process: fork/exec ./opctl: no such file or directory
exit status 1
ContainerExited Id='1b2b5aff4e3c477c9b41f55336b0f4d2' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' ExitCode='1' Timestamp='2020-02-14T12:11:54Z'

OpErred Id='d9221ab45dd841af8bef461c39ff2405' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Timestamp='2020-02-14T12:11:54Z' Msg='nonzero container exit code. Exit code was: 1'

OpEnded Id='d9221ab45dd841af8bef461c39ff2405' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Outcome='FAILED' Timestamp='2020-02-14T12:11:54Z'


1 ↩
```

I then ran `opctl run build` and then `opctl run dev` and got an error in the dev step.

```
OpStarted Id='c62ac48d16a84207afc43e6e2ac4c6c7' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Timestamp='2020-02-14T14:24:37Z'

ContainerStarted Id='58aaf93c1d9f45898122cc4010ae8118' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Timestamp='2020-02-14T14:24:37Z'

1.13: Pulling from library/golang
Digest: sha256:9295ba678e3764d79ac0aeabdbcf281a91933c81c8de29387d8a2f557e256cdb
Status: Image is up to date for golang:1.13
API server listening at: [::]:40000
OpStarted Id='2f569117a62a426c9db196d6b7986daa' OpRef='/root/opctl/ops/github.com/opspec-pkgs/uuid.v4.generate#1.1.0' Timestamp='2020-02-14T14:24:58Z'

ContainerStarted Id='da1e8634e913488fbdc99e148ff2fed5' OpRef='/root/opctl/ops/github.com/opspec-pkgs/uuid.v4.generate#1.1.0' Timestamp='2020-02-14T14:24:58Z'

1.1.0: Pulling from opspecpkgs/uuid.v4.generate
...
61bc0d772716: Pull complete
Digest: sha256:051b1fb0a3eeb44ccdf5238fe77e14f883cb88b51ad1a7cbe62abbe65a12696e
Status: Downloaded newer image for opspecpkgs/uuid.v4.generate:1.1.0
module.js:557
    throw err;
    ^

Error: Cannot find module '/cmd.js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
ContainerExited Id='da1e8634e913488fbdc99e148ff2fed5' OpRef='/root/opctl/ops/github.com/opspec-pkgs/uuid.v4.generate#1.1.0' ExitCode='1' Timestamp='2020-02-14T14:25:02Z'

OpErred Id='2f569117a62a426c9db196d6b7986daa' OpRef='/root/opctl/ops/github.com/opspec-pkgs/uuid.v4.generate#1.1.0' Timestamp='2020-02-14T14:25:02Z' Msg='nonzero container exit code. Exit code was: 1'

OpEnded Id='2f569117a62a426c9db196d6b7986daa' OpRef='/root/opctl/ops/github.com/opspec-pkgs/uuid.v4.generate#1.1.0' Outcome='FAILED' Timestamp='2020-02-14T14:25:02Z'


ContainerExited Id='58aaf93c1d9f45898122cc4010ae8118' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' ExitCode='0' Timestamp='2020-02-14T14:25:03Z'

OpEnded Id='c62ac48d16a84207afc43e6e2ac4c6c7' OpRef='/Users/cameronlittle/Dev/opctl/cli/.opspec/dev' Outcome='SUCCEEDED' Timestamp='2020-02-14T14:25:03Z'
```

**Comment by chrisdostert** [comment]
This is a mono repo, there’s multiple projects. If you are working on the cli, you would cd to cli directory and ‘opctl run build’. The cli is mostly a wrapper around the go sdk which you can work on by cd’ing to sdks/go and ‘opctl run build’. Each project has its own ops.

**Comment by chrisdostert** [comment]
Unrelated but what version of opctl are you on? ‘opctl -v’

**Comment by apexskier** [comment]
I'm on version `0.1.27`

**Comment by apexskier** [comment]
Yep, I'm running from the CLI directory

> From the cli directory

I'm mostly filing this because the CONTRIBUTION.md docs don't have any info about how to build.

**Comment by chrisdostert** [comment]
Well.. that's not really true; The [top level CONTRIBUTING.md](https://github.com/opctl/opctl/blob/master/CONTRIBUTING.md) calls out that the repo is a mono repo and notes the directory structure. Within that each project has it's own `CONTRIBUTING.md`. I think the issue maybe stemmed from the links not working properly. Can you verify that if the links to [CLI](https://github.com/opctl/opctl/blob/master/cli/CONTRIBUTING.md) , [webapp](https://github.com/opctl/opctl/blob/master/webapp/CONTRIBUTING.md), [go sdk](https://github.com/opctl/opctl/blob/master/sdks/go/CONTRIBUTING.md), [js sdk](https://github.com/opctl/opctl/blob/master/sdks/js/CONTRIBUTING.md), and [react sdk](https://github.com/opctl/opctl/blob/master/sdks/react/CONTRIBUTING.md) were working, you'd have been sorted? If so that's a simple fix. If not, can you more clearly describe what you see as missing so we can fully action it? Thanks

**Comment by apexskier** [comment]
What's missing is documentation about how to develop. Some examples of questions that are hard to answer:

- How do I produce a locally built opctl binary I can execute?
- How do I make sure my SDK changes are accessible in the CLI?
- I'd assume there's a core opctl process running that the CLI is interacting with - where does that live?
- What relationship does the [api directory](https://github.com/opctl/opctl/tree/master/api) have with source code?
- How do I run or connect to the api?

There's also the issue I had with `opctl run dev` in the cli - the op it runs throws errors.

**Comment by chrisdostert** [comment]
As an initial step i've added a `How do I...` section to each `Contributing.md`. This itself doesn't address all but does address some of your line items above. Still chewing on how best to cover some of the others. The 3rd and 5th items are maybe best as general (i.e. published as documentation on https://opctl.io)

**Comment by chrisdostert** [comment]
For tracking....
Done:
1) How do I produce a locally built opctl binary I can execute? 
https://github.com/opctl/opctl/blob/master/cli/CONTRIBUTING.md#build

1) How do I make sure my SDK changes are accessible in the CLI?
https://github.com/opctl/opctl/blob/master/cli/CONTRIBUTING.md#pull-in-local-go-sdk-changes

1) There's also the issue I had with opctl run dev in the cli - the op it runs throws errors.
it was in a state it required manual configuration before running. It's been updated so batteries are included by default now.

Outstanding:
- I'd assume there's a core opctl process running that the CLI is interacting with - where does that live?
- How do I run or connect to the api?
