### ISSUE TITLE
No documentation about the current webapp

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#695]
According to [CONTRIBUTING.md](https://github.com/opctl/opctl/blob/master/CONTRIBUTING.md), there's a webapp.

> Webapp included in the opctl binary.

What is this? How do I use it?

**Comment by chrisdostert** [comment]
there is one but it's deprecated so hence intentionally not documented in user docs. It was basically a browser version of the CLI functionality combined running in a resizable terminal grid. It's actively being re-written to allow exploring/managing an entire opctl workspace and includes a WYSIWYG designer/builder/debugger for ops. You can play around w/ the WIP via `opctl self-update -c alpha` and browsing to `localhost:42224`.
