### ISSUE TITLE
Broken link on opspec docs webpage

### ISSUE THREAD

**Issue by drewandersen** [opctl/opctl#703]
## 🐛 Bug Report

Broken link on webpage.

## To Reproduce

1. Visit https://opctl.io/docs/opspec/introduction/
1. Under `run` -> `op`, click on `inputs`
1. Receive a 404 here: https://opctl.io/docs/opspec/introduction/reference/structure/op-directory/op/call/op/index#inputs

**Comment by chrisdostert** [comment]
@drewandersen thanks. 
found 2 issues:
1) It turns out docusaurus link behavior differs between dev and production builds. I had to update relative links to include `.md` extensions to get them to work properly in the production build.
2) the links to the op call page were off.
