### ISSUE TITLE
Running `op install` twice wipes out op file contents

### ISSUE THREAD

**Issue by ddenisen** [opctl/opctl#718]
## 🐛 Bug Report

Running `opctl op install [path-to-op]` if the referenced op is already installed in the local directory results in the files associated with the referenced op (`op.yml`, etc) to be wiped out to zero length. Subsequently running `opctl run [path-to-op]` silently fails with no error code.

I've verified this bug exists in versions 0.1.27 and 0.1.28.

## To Reproduce

1. Create and enter an empty directory locally:
    ```
    > mkdir op-install-test && cd op-install-test
    ```
2. Run `op install`:
    ```
    > opctl op install github.com/opspec-pkgs/fs.stat#1.0.0
    ```
3. Verify op file is present and non-empty:
    ```
    > cat .opspec/github.com/opspec-pkgs/fs.stat#1.0.0/op.yml | wc
          50     101    1043
    ```
4. Re-run `op install` for the same op:
    ```
    > opctl op install github.com/opspec-pkgs/fs.stat#1.0.0
    ```
    Observe that the command silently succeeds with 0 exit status.

## Expected behavior

Subsequent call `opctl op install` for an already-installed op with the same version should be treated as a no-op.

## Actual Behavior

The op file contents are now wiped out:
    ```
    cat .opspec/github.com/opspec-pkgs/fs.stat#1.0.0/op.yml | wc
           0       0       0
    ```

Subsequently running the affected op results in the run command succeeding silently without actually performing any work:
```
> op run github.com/opspec-pkgs/fs.stat#1.0.0
OpStarted Id='88ccc489d7554d67b557b12c43eabf0a' OpRef='/Users/dmitry/Code/optest/.opspec/github.com/opspec-pkgs/fs.stat#1.0.0' Timestamp='2020-04-02T04:33:23Z'

OpEnded Id='88ccc489d7554d67b557b12c43eabf0a' OpRef='/Users/dmitry/Code/optest/.opspec/github.com/opspec-pkgs/fs.stat#1.0.0' Outcome='SUCCEEDED' Timestamp='2020-04-02T04:33:23Z'
```

This is a pretty serious issue because it may result in automated scripts that rely on op malfunctioning quietly, for example in CI environments where multiple CI task might want to install and run the same op. In that case, the second task will end up not performing any actual work but give off the appearance of succeeding.

**Comment by chrisdostert** [comment]
@ddenisen thanks for filing. Fix on the way
