### ISSUE TITLE
official dood image example doesn't work

### ISSUE THREAD

**Issue by chrisdostert** [opctl/opctl#720]
## 🐛 Bug Report
When using the opctl/opctl:0.1.29-dood image and running ops referencing embedded files, the files can't be resolved. 

## To Reproduce

1. run [dood image example](https://opctl.io/docs/setup/docker#dood-variant-experimental-paths-might-not-be-found) i.e. `docker run -v /var/run/docker.sock:/var/run/docker.sock opctl/opctl:0.1.29-dood opctl run github.com/opspec-pkgs/uuid.v4.generate#1.1.0`

## Expected behavior
 op runs to completion

## Actual Behavior
errors with
```
module.js:557
    throw err;
    ^

Error: Cannot find module '/cmd.js'
```

note: the dind image works fine `docker run --privileged opctl/opctl:0.1.29-dind opctl run github.com/opspec-pkgs/uuid.v4.generate#1.1.0`

**Comment by lmarszal** [comment]
Every path mounted inside op's containers needs to be mounted into opctl server container too.
Opctl is using `/root/opctl` work directory (downloads remote ops refs there and mount it's files inside the container) - so it has to be mounted from the host path in order to work correctly.

This command works for me:
```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/opctl opctl/opctl:0.1.29-dood opctl run github.com/opspec-pkgs/uuid.v4.generate#1.1.0
```

**Comment by chrisdostert** [comment]
what if we automated this requirement?

**Comment by chrisdostert** [comment]
can you think of a way to automate it?

**Comment by chrisdostert** [comment]
we can revisit later if we want to. closing.
