### ISSUE TITLE
Improve data resolution failure errors

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#855]
## 🚀 Feature

Currently, when someone enters an invalid op name, they see this:

```
Get "https://dummyOpRef/info/refs?service=git-upload-pack": dial tcp: lookup dummyOpRef on 127.0.0.11:53: no such host
```

This is a common source of confusion, as it looks like an issue related to their internet connection or something with git. Additionally, because opctl attempts to resolve the url, there's a several second timeout before this is thrown, which is annoying and causes tests of the functionality to be quite slow.

I also have issues with this test locally, which might be able to be fixed:

![Screen Shot 2021-01-05 at 16 45 35](https://user-images.githubusercontent.com/329222/103666843-71909200-4f75-11eb-996f-853cd5682e5a.png)

## Ideas for resolution

Currently, everything that doesn't resolve locally is checked with a git clone.

~I think the general approach should having a more well defined op "ref" syntax that can be parsed.~

I think it's reasonable to skip this check for absolute or relative file paths (starting with `/` or `./`. ~It's probably acceptable to not do a network check for strings that don't have a tld or strings that don't contain path parameters `/`, which generally won't resolve to valid opspec urls.~ Even better, since references without a version tag fail, opctl could just not do git resolution if [`parseRef`](https://github.com/opctl/opctl/blob/97795bbe3dfd5899cdbb972aeb19067fb3b0ed45/sdks/go/data/git/parseRef.go#L21) doesn't find a version.

The current architecture of data resolution makes this not great still, since every failed op reference will appear as a git resolution failure. I don't really want a mistyped local op, or running from the wrong directory to look like something's wrong with a git url. A larger change could be to expand the data resolver to have two methods: `ShouldTryResolve` and `TryResolve`. `ShouldTryResolve` would be tried first, and only if it succeeds would `TryResolve` be checked. Or, results from all providers could be displayed on failures, to indicate that git urls aren't the only issue.

**Comment by chrisdostert** [comment]
related https://github.com/opctl/opctl/issues/770
