### ISSUE TITLE
opctl on windows 10 unable to run hello-world op

### ISSUE THREAD

**Issue by mahadioct** [opctl/opctl#888]
## 🐛 Bug Report

Thank you for creating opctl.
I am trying to use opctl and i am started with this tutorial - https://opctl.io/docs/training/hello-world.

I am using windows 10 pro, docker latest version and this is the error I got.

$ opctl ls
REF     DESCRIPTION
Unable to resolve '.opspec'; error was Get "https://.opspec/info/refs?service=git-upload-pack": dial tcp: lookup .opspec: no such host
<img width="458" alt="Capture" src="https://user-images.githubusercontent.com/16687153/111115294-96653f00-858e-11eb-9514-56634679f060.PNG">

Can you please help ?

**Comment by chrisdostert** [comment]
Can you make sure you're following the tutorial exactly? Step 3 is `ls`, not `opctl ls`; I think that might be where you're getting off course.

**Comment by mahadioct** [comment]
Thank you for your response.
I have also try ls ... but getting another error...
![image](https://user-images.githubusercontent.com/16687153/111222478-18dd1580-8606-11eb-88e2-6a57ee6e4907.png)

**Comment by chrisdostert** [comment]
Have you tried running in WSL 2?

**Comment by chrisdostert** [comment]
I would highly recommend using WSL 2; that's the best linux container experience on windows from what i've heard from all windows users. We actually are planning to start requiring it next release (for windows users).

**Comment by chrisdostert** [comment]
closing as [windows support is now based on WSL](https://opctl.io/docs/setup/bare-metal#windows)
