### ISSUE TITLE
Node locking mechanism doesn't ensure process is opctl

### ISSUE THREAD

**Issue by bkielbasa** [opctl/opctl#913]
## 🐛 Bug Report

When I want to run opctl command I receive the following message:

```
$ opctl run dev
Post "http://127.0.0.1:42224/api/ops/starts": dial tcp 127.0.0.1:42224: connect: connection refused
````

I tried to run this command but without luck

```
$ opctl events
dial tcp 127.0.0.1:42224: connect: connection refused
```

opctl Version: 0.1.47
docker up and running (restarted)
I'm running on MacOS

**Comment by chrisdostert** [comment]
Hi @bkielbasa , my first guess is your opctl CLI thinks a node should be running based on the contents of the `$OPCTL_DATA_DIR/pid.lock`. I'll bet deleting that file will fix it. 

You can find where your data dir currently is set via running `opctl` from your command line and you'll see something like `--data-dir            Path of dir used to store opctl data (env $OPCTL_DATA_DIR) (default "/Users/chrisdostert/Library/Application Support/opctl")`

**Comment by bkielbasa** [comment]
yeah, that's solved my problem. Thanks. IMO it's a good idea to add a notice about how to fix it. Otherwise, It's hard to reason about the root cause.
Thanks again!

**Comment by chrisdostert** [comment]
For sure, this is honestly the only time I've heard of that happening so you just got "lucky" I think. Let's leave this issue open so we can create a proper fix to prevent it happening to anyone else.
