### ISSUE TITLE
Don't docker pull unless necessary

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#920]
## 💥 Proposal

We currently experience a high number of docker rate limiting errors (INFRA-1870), which I suspect is due to opctl's policy of pulling every time a container is run. I've hit this enough that I've applied this change to my branch - https://github.com/opctl/opctl/commit/1fdde9f63ae7b96fa5debbc8bee974f289194a60.

I'd propose we skip pulling if (a) the image is tagged and (b) the image has been pulled locally.

**Comment by chrisdostert** [comment]
The reason we chose this tact originally was because without it you have non-deterministic runs. Someone can run an op and have totally different behavior from the next person because they pulled the images at different times initially. So there's pros and cons. We support globally auth'ing to an image source via the [auth](https://opctl.io/docs/reference/cli/auth/index) command so personally I'd advocate we keep the current logic and advise to auth if you run into rate limiting; current logic seems most "correct" to me; just my vote though.

**Comment by psamaan** [comment]
I would like to understand the speed argument though. If this truly does improve performance then it's a win regardless of the rate limiting concern. Does it currently still affect performance to pull even if all layers are unchanged and available locally?

**Comment by chrisdostert** [comment]
@psamaan It doesn't pull anything unless there's changes so no; we're talking about a no-op network request in the general case.

**Comment by apexskier** [comment]
I personally am not concerned by the non-determinism argument. I also could have an op work yesterday, then not work today, which is a con that is helped by this change.

---

This definitely improves performance. I wrote a benchmark test that compares the pull that opctl previously did with an image inspect:

```
BenchmarkImagePull-16       	       6	1906775450 ns/op
BenchmarkImageInspect-16    	    5701	   2267023 ns/op
```

That's 1.9 seconds to do a pull, 0.0023 seconds to inspect.

<details>

<summary>Benchmark code</summary>

```sh
go test -bench=. -benchtime=10s ./...
```

```go
package main

import (
	"context"
	"testing"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
)

func BenchmarkImagePull(b *testing.B) {
	ctx := context.Background()
	dc, err := client.NewClientWithOpts(client.FromEnv)
	if err != nil {
		b.Fatal(err)
	}

	// initial pull to cache image
	imagePullResp, err := dc.ImagePull(
		ctx,
		"golang:1.15",
		types.ImagePullOptions{},
	)
	if err != nil {
		panic(err)
	}
	imagePullResp.Close()

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		imagePullResp, err := dc.ImagePull(
			ctx,
			"golang:1.15",
			types.ImagePullOptions{},
		)
		if err != nil {
			b.Fatal(err)
		}
		imagePullResp.Close()
	}
}

func BenchmarkImageInspect(b *testing.B) {
	ctx := context.Background()
	dc, err := client.NewClientWithOpts(client.FromEnv)
	if err != nil {
		b.Fatal(err)
	}

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		_, _, _ = dc.ImageInspectWithRaw(ctx, "golang:1.15")
	}
}
```

</details>

**Comment by chrisdostert** [comment]
> I personally am not concerned by the non-determinism argument. I also could have an op work yesterday, then not work today for the same reason, which is a con that is helped by this change. Unless we require full digests in image references, this will always be a potential issue. Rate limiting is a more common error, in my experience, and there's not an easy way to work around it (we already auth with docker in our build environments). Non-determinism is easy to work around by adding a stronger image ref.
> 
> This definitely improves performance. I wrote a benchmark test that compares the pull that opctl previously did with an image inspect:
> 
> ```
> BenchmarkImagePull-16       	       6	1906775450 ns/op
> BenchmarkImageInspect-16    	    5701	   2267023 ns/op
> ```
> 
> That's 1.9 seconds to do a pull, 0.0023 seconds to inspect. With the number of containers some ops run, it really adds up! (since this does do a network request, it'll probably be less dramatic in the US)
> 
> Benchmark code

@apexskier  we auth opctl in our build environments actually so I'm guessing the issue you were solving here won't be fixed by this.

**Comment by chrisdostert** [comment]
Also, what you're describing isn't the same thing. What I'm describing is two people running the same op *at the same time* having different behavior. That's a much bigger evil in my opinion than running it a different day and seeing different behavior IMHO because it leads to people wondering why something is working for them and not the other person.

**Comment by chrisdostert** [comment]
This already got merged in per PR above so if we want to revisit we can do it separately. Closing the loop here.
