### ISSUE TITLE
Docker in docker is broken

### ISSUE THREAD

**Issue by apexskier** [opctl/opctl#996]
## 🐛 Bug Report

Running opctl in docker doesn't work.

## To Reproduce

(Write your steps here:)

1. Run 
   ```
   docker run --privileged opctl/opctl:0.1.48-dind opctl node create
   ```

## Expected behavior

Runs sucessfully

## Actual Behavior

Fails:

```
...
running provided cmd
runtime error: slice bounds out of range [:13] with length 1
↩ 1 (ERROR)
```

## Other notes

This is a minimal reproduction of behavior seen in forgeserv's dev op, as well as when running the example script from https://opctl.io/docs/setup/docker/.

I'm on macOS docker desktop 4.3.2 (I'm not willing to downgrade because of log4j vulnerability detection)

**Comment by chrisdostert** [comment]
We'll have to update for the breaking change docker introduced in docker for mac 4.3. If anyone finds this thread and is looking for alternatives, downgrading to pre docker 4.3 will work in the meantime.

**Comment by chrisdostert** [comment]
Can't seem to repro this anymore; many docker updates since. Will close it out for now.
